export const EXERCISE_CATALOG = [
  { name: 'Squat', category: 'Strength', met: 6.0 },
  { name: 'Bench Press', category: 'Strength', met: 5.0 },
  { name: 'Deadlift', category: 'Strength', met: 6.0 },
  { name: 'Barbell Row', category: 'Strength', met: 4.5 },
  { name: 'Overhead Press', category: 'Strength', met: 4.5 },
  { name: 'Pull-up', category: 'Strength', met: 4.0 },
  { name: 'Chin-up', category: 'Strength', met: 4.0 },
  { name: 'Bicep Curl', category: 'Strength', met: 3.5 },
  { name: 'Tricep Extension', category: 'Strength', met: 3.5 },
  { name: 'Lat Pulldown', category: 'Strength', met: 4.0 },
  { name: 'Leg Press', category: 'Strength', met: 5.0 },
  { name: 'Lunges', category: 'Strength', met: 5.0 },
  { name: 'Plank', category: 'Strength', met: 3.0 },
  { name: 'Front Squat', category: 'Strength', met: 6.0 },
  { name: 'Goblet Squat', category: 'Strength', met: 5.0 },
  { name: 'Romanian Deadlift', category: 'Strength', met: 5.5 },
  { name: 'Hip Thrust', category: 'Strength', met: 5.0 },
  { name: 'Glute Bridge', category: 'Strength', met: 3.5 },
  { name: 'Leg Extension', category: 'Strength', met: 3.5 },
  { name: 'Leg Curl', category: 'Strength', met: 3.5 },
  { name: 'Calf Raise', category: 'Strength', met: 3.5 },
  { name: 'Chest Fly', category: 'Strength', met: 3.5 },
  { name: 'Incline Bench Press', category: 'Strength', met: 5.0 },
  { name: 'Dumbbell Press', category: 'Strength', met: 4.5 },
  { name: 'Push-up', category: 'Strength', met: 3.8 },
  { name: 'Dip', category: 'Strength', met: 4.0 },
  { name: 'Face Pull', category: 'Strength', met: 3.5 },
  { name: 'Cable Row', category: 'Strength', met: 4.0 },
  { name: 'Dumbbell Row', category: 'Strength', met: 4.0 },
  { name: 'Lateral Raise', category: 'Strength', met: 3.0 },
  { name: 'Shoulder Shrug', category: 'Strength', met: 3.0 },
  { name: 'Hammer Curl', category: 'Strength', met: 3.5 },
  { name: 'Preacher Curl', category: 'Strength', met: 3.5 },
  { name: 'Skull Crusher', category: 'Strength', met: 3.5 },
  { name: 'Tricep Pushdown', category: 'Strength', met: 3.5 },
  { name: 'Russian Twist', category: 'Strength', met: 3.0 },
  { name: 'Crunch', category: 'Strength', met: 2.8 },
  { name: 'Sit-up', category: 'Strength', met: 3.0 },
  { name: 'Dead Bug', category: 'Strength', met: 2.8 },
  { name: 'Kettlebell Swing', category: 'Strength', met: 8.0 },
  { name: 'Clean and Press', category: 'Strength', met: 8.0 },
  { name: 'Burpee', category: 'Strength', met: 8.0 },
  { name: 'Running', category: 'Cardio', met: 9.8 },
  { name: 'Jogging', category: 'Cardio', met: 7.0 },
  { name: 'Cycling', category: 'Cardio', met: 7.5 },
  { name: 'Jump Rope', category: 'Cardio', met: 10.0 },
  { name: 'Rowing Machine', category: 'Cardio', met: 7.0 },
  { name: 'Elliptical', category: 'Cardio', met: 5.0 },
  { name: 'Stair Climber', category: 'Cardio', met: 8.0 },
  { name: 'Swimming', category: 'Cardio', met: 8.0 },
  { name: 'Walking', category: 'Cardio', met: 3.5 },
  { name: 'Brisk Walking', category: 'Cardio', met: 4.5 },
  { name: 'Hiking', category: 'Cardio', met: 6.0 },
  { name: 'Treadmill Walking', category: 'Cardio', met: 4.0 },
  { name: 'Treadmill Running', category: 'Cardio', met: 9.8 },
  { name: 'Indoor Cycling', category: 'Cardio', met: 7.5 },
  { name: 'Mountain Biking', category: 'Cardio', met: 8.5 },
  { name: 'Spin Class', category: 'Cardio', met: 8.5 },
  { name: 'Water Aerobics', category: 'Cardio', met: 5.5 },
  { name: 'Dancing', category: 'Cardio', met: 5.5 },
  { name: 'Zumba', category: 'Cardio', met: 6.5 },
  { name: 'Tennis', category: 'Cardio', met: 7.3 },
  { name: 'Basketball', category: 'Cardio', met: 6.5 },
  { name: 'Soccer', category: 'Cardio', met: 7.0 },
  { name: 'Badminton', category: 'Cardio', met: 5.5 },
  { name: 'Boxing', category: 'Cardio', met: 7.8 },
  { name: 'Kickboxing', category: 'Cardio', met: 7.5 },
  { name: 'Hula Hooping', category: 'Cardio', met: 5.5 },
  { name: 'Jumping Jacks', category: 'Cardio', met: 7.0 },
  { name: 'Hiking Uphill', category: 'Cardio', met: 7.0 },
  { name: 'Cross-country Skiing', category: 'Cardio', met: 8.0 },
  { name: 'Water Polo', category: 'Cardio', met: 10.0 },
  { name: 'Sumo Deadlift', category: 'Strength', met: 5.5 },
  { name: 'Trap Bar Deadlift', category: 'Strength', met: 5.5 },
  { name: 'Good Morning', category: 'Strength', met: 4.0 },
  { name: 'Back Extension', category: 'Strength', met: 3.5 },
  { name: 'Single-leg Romanian Deadlift', category: 'Strength', met: 4.0 },
  { name: 'Bulgarian Split Squat', category: 'Strength', met: 5.0 },
  { name: 'Step-up', category: 'Strength', met: 4.5 },
  { name: 'Walking Lunge', category: 'Strength', met: 5.0 },
  { name: 'Reverse Lunge', category: 'Strength', met: 4.5 },
  { name: 'Leg Press Calf Raise', category: 'Strength', met: 3.5 },
  { name: 'Hip Abduction', category: 'Strength', met: 3.0 },
  { name: 'Hip Adduction', category: 'Strength', met: 3.0 },
  { name: 'Glute Kickback', category: 'Strength', met: 3.5 },
  { name: 'Smith Machine Squat', category: 'Strength', met: 5.0 },
  { name: 'Hack Squat', category: 'Strength', met: 5.0 },
  { name: 'Sissy Squat', category: 'Strength', met: 4.0 },
  { name: 'Close-grip Bench Press', category: 'Strength', met: 4.5 },
  { name: 'Decline Bench Press', category: 'Strength', met: 5.0 },
  { name: 'Dumbbell Fly', category: 'Strength', met: 3.5 },
  { name: 'Incline Dumbbell Press', category: 'Strength', met: 4.5 },
  { name: 'Pec Deck', category: 'Strength', met: 3.5 },
  { name: 'Arnold Press', category: 'Strength', met: 4.0 },
  { name: 'Front Raise', category: 'Strength', met: 3.0 },
  { name: 'Rear Delt Fly', category: 'Strength', met: 3.0 },
  { name: 'Upright Row', category: 'Strength', met: 3.5 },
  { name: 'Barbell Curl', category: 'Strength', met: 3.5 },
  { name: 'Concentration Curl', category: 'Strength', met: 3.0 },
  { name: 'Cable Curl', category: 'Strength', met: 3.5 },
  { name: 'Reverse Curl', category: 'Strength', met: 3.0 },
  { name: 'Overhead Tricep Extension', category: 'Strength', met: 3.5 },
  { name: 'Diamond Push-up', category: 'Strength', met: 4.0 },
  { name: 'Assisted Pull-up', category: 'Strength', met: 3.5 },
  { name: 'Inverted Row', category: 'Strength', met: 3.5 },
  { name: 'Straight-arm Pulldown', category: 'Strength', met: 3.5 },
  { name: 'Renegade Row', category: 'Strength', met: 4.5 },
  { name: 'Farmer Carry', category: 'Strength', met: 5.0 },
  { name: 'Turkish Get-up', category: 'Strength', met: 5.0 },
  { name: 'Dumbbell Snatch', category: 'Strength', met: 7.0 },
  { name: 'Thruster', category: 'Strength', met: 7.0 },
  { name: 'Mountain Climber', category: 'Strength', met: 7.0 },
  { name: 'Bicycle Crunch', category: 'Strength', met: 3.0 },
  { name: 'Leg Raise', category: 'Strength', met: 3.0 },
  { name: 'Hanging Knee Raise', category: 'Strength', met: 3.5 },
  { name: 'Side Plank', category: 'Strength', met: 3.0 },
  { name: 'Bird Dog', category: 'Strength', met: 2.8 },
  { name: 'Pallof Press', category: 'Strength', met: 3.0 },
  { name: 'Battle Ropes', category: 'Cardio', met: 9.0 },
  { name: 'Sled Push', category: 'Cardio', met: 8.0 },
  { name: 'Sled Pull', category: 'Cardio', met: 7.5 },
  { name: 'Boxing, punching bag', category: 'Cardio', met: 7.8 },
  { name: 'Martial Arts', category: 'Cardio', met: 10.0 },
  { name: 'Wrestling', category: 'Cardio', met: 6.0 },
  { name: 'Racquetball', category: 'Cardio', met: 7.0 },
  { name: 'Squash', category: 'Cardio', met: 7.3 },
  { name: 'Volleyball', category: 'Cardio', met: 4.0 },
  { name: 'Beach Volleyball', category: 'Cardio', met: 8.0 },
  { name: 'Softball', category: 'Cardio', met: 5.0 },
  { name: 'Flag Football', category: 'Cardio', met: 7.0 },
  { name: 'Skating', category: 'Cardio', met: 7.0 },
  { name: 'Rollerblading', category: 'Cardio', met: 7.5 },
  { name: 'Snowboarding', category: 'Cardio', met: 5.3 },
  { name: 'Downhill Skiing', category: 'Cardio', met: 5.3 },
  { name: 'Cross-country Ski Machine', category: 'Cardio', met: 6.8 },
  { name: 'Kayaking', category: 'Cardio', met: 5.0 },
  { name: 'Canoeing', category: 'Cardio', met: 3.5 },
  { name: 'Paddleboarding', category: 'Cardio', met: 6.0 },
  { name: 'Surfing', category: 'Cardio', met: 3.0 },
  { name: 'Water jogging', category: 'Cardio', met: 6.0 },
  { name: 'Freestyle swimming', category: 'Cardio', met: 8.0 },
  { name: 'Breaststroke swimming', category: 'Cardio', met: 10.0 },
  { name: 'Lap swimming, leisurely', category: 'Cardio', met: 6.0 },
  { name: 'Jump rope, moderate', category: 'Cardio', met: 11.8 },
  { name: 'Jump rope, fast', category: 'Cardio', met: 12.3 },
  { name: 'Stair climbing', category: 'Cardio', met: 8.8 },
  { name: 'Step aerobics', category: 'Cardio', met: 6.5 },
  { name: 'Aerobics, low impact', category: 'Cardio', met: 5.0 },
  { name: 'Aerobics, high impact', category: 'Cardio', met: 7.3 },
  { name: 'HIIT', category: 'Cardio', met: 8.0 },
  { name: 'Circuit training', category: 'Cardio', met: 6.0 },
  { name: 'Boot camp workout', category: 'Cardio', met: 7.0 },
  { name: 'Pilates', category: 'Cardio', met: 3.0 },
  { name: 'Yoga, Hatha', category: 'Cardio', met: 2.5 },
  { name: 'Yoga, power', category: 'Cardio', met: 4.0 },
  { name: 'Tai chi', category: 'Cardio', met: 3.0 },
  { name: 'Marching in place', category: 'Cardio', met: 3.5 },
  { name: 'Running, intervals', category: 'Cardio', met: 11.0 },
  { name: 'Running, uphill', category: 'Cardio', met: 11.0 },
  { name: 'Trail running', category: 'Cardio', met: 9.0 },
  { name: 'Track running', category: 'Cardio', met: 9.8 },
  { name: 'Stroller walking', category: 'Cardio', met: 3.5 },
  { name: 'Dog walking', category: 'Cardio', met: 3.0 },
  { name: 'Recumbent cycling', category: 'Cardio', met: 5.0 },
  { name: 'Stationary bike, vigorous', category: 'Cardio', met: 8.8 },
  { name: 'Rowing, vigorous', category: 'Cardio', met: 8.5 },
  { name: 'Dance cardio', category: 'Cardio', met: 7.0 },
  { name: 'Line dancing', category: 'Cardio', met: 4.5 },
  { name: 'Ballet', category: 'Cardio', met: 5.0 },
  { name: 'Cheerleading', category: 'Cardio', met: 6.0 },
  { name: 'Gardening', category: 'Cardio', met: 3.5 },
  { name: 'Raking leaves', category: 'Cardio', met: 4.0 },
  { name: 'Mowing lawn', category: 'Cardio', met: 5.5 },
]

export const CATEGORIES = ['Strength', 'Cardio']

export const MET_TABLE = Object.fromEntries(
  EXERCISE_CATALOG.map((exercise) => [exercise.name, exercise.met])
)
MET_TABLE.Default = 5.0

export function getMET(exercise) {
  return MET_TABLE[exercise] || MET_TABLE.Default
}

export function calculateCalories(sets, bodyWeightKg, durationMinutes) {
  if (!sets || sets.length === 0) return 0
  const avgMet = sets.reduce((sum, s) => sum + getMET(s.exercise), 0) / sets.length
  const durationHours = durationMinutes / 60
  return Math.round(avgMet * bodyWeightKg * durationHours)
}