const CUSTOM_EXERCISES_KEY = 'hercurles:custom-exercises'

export const EXERCISE_CATALOG = [

  // Strength exercises
  { name: 'Squat', category: 'Strength', met: 6.0 },
  { name: 'Bench Press', category: 'Strength', met: 5.0 },
  { name: 'Deadlift', category: 'Strength', met: 6.0 },
  { name: 'Barbell Row', category: 'Strength', met: 4.5 },
  { name: 'Overhead Press', category: 'Strength', met: 4.5 },
  { name: 'Pull-up', category: 'Strength', met: 4.0 },
  { name: 'Chin-up', category: 'Strength', met: 4.0 },
  { name: 'Bicep Curl', category: 'Strength', met: 3.5 },
  { name: 'Tricep Extension', category: 'Strength', met: 3.5 },
  { name: 'Lat Pulldown', category: 'Strength', met: 4.0 },
  { name: 'Leg Press', category: 'Strength', met: 5.0 },
  { name: 'Lunges', category: 'Strength', met: 5.0 },
  { name: 'Plank', category: 'Strength', met: 3.0 },
  { name: 'Front Squat', category: 'Strength', met: 6.0 },
  { name: 'Goblet Squat', category: 'Strength', met: 5.0 },
  { name: 'Romanian Deadlift', category: 'Strength', met: 5.5 },
  { name: 'Hip Thrust', category: 'Strength', met: 5.0 },
  { name: 'Glute Bridge', category: 'Strength', met: 3.5 },
  { name: 'Leg Extension', category: 'Strength', met: 3.5 },
  { name: 'Leg Curl', category: 'Strength', met: 3.5 },
  { name: 'Calf Raise', category: 'Strength', met: 3.5 },
  { name: 'Chest Fly', category: 'Strength', met: 3.5 },
  { name: 'Incline Bench Press', category: 'Strength', met: 5.0 },
  { name: 'Dumbbell Press', category: 'Strength', met: 4.5 },
  { name: 'Push-up', category: 'Strength', met: 3.8 },
  { name: 'Dip', category: 'Strength', met: 4.0 },
  { name: 'Face Pull', category: 'Strength', met: 3.5 },
  { name: 'Cable Row', category: 'Strength', met: 4.0 },
  { name: 'Dumbbell Row', category: 'Strength', met: 4.0 },
  { name: 'Lateral Raise', category: 'Strength', met: 3.0 },
  { name: 'Shoulder Shrug', category: 'Strength', met: 3.0 },
  { name: 'Hammer Curl', category: 'Strength', met: 3.5 },
  { name: 'Preacher Curl', category: 'Strength', met: 3.5 },
  { name: 'Skull Crusher', category: 'Strength', met: 3.5 },
  { name: 'Tricep Pushdown', category: 'Strength', met: 3.5 },
  { name: 'Russian Twist', category: 'Strength', met: 3.0 },
  { name: 'Crunch', category: 'Strength', met: 2.8 },
  { name: 'Sit-up', category: 'Strength', met: 3.0 },
  { name: 'Dead Bug', category: 'Strength', met: 2.8 },
  { name: 'Kettlebell Swing', category: 'Strength', met: 8.0 },
  { name: 'Clean and Press', category: 'Strength', met: 8.0 },
  { name: 'Burpee', category: 'Strength', met: 8.0 },
  { name: 'Sumo Deadlift', category: 'Strength', met: 5.5 },
  { name: 'Trap Bar Deadlift', category: 'Strength', met: 5.5 },
  { name: 'Good Morning', category: 'Strength', met: 4.0 },
  { name: 'Back Extension', category: 'Strength', met: 3.5 },
  { name: 'Single-leg Romanian Deadlift', category: 'Strength', met: 4.0 },
  { name: 'Bulgarian Split Squat', category: 'Strength', met: 5.0 },
  { name: 'Step-up', category: 'Strength', met: 4.5 },
  { name: 'Walking Lunge', category: 'Strength', met: 5.0 },
  { name: 'Reverse Lunge', category: 'Strength', met: 4.5 },
  { name: 'Leg Press Calf Raise', category: 'Strength', met: 3.5 },
  { name: 'Hip Abduction', category: 'Strength', met: 3.0 },
  { name: 'Hip Adduction', category: 'Strength', met: 3.0 },
  { name: 'Glute Kickback', category: 'Strength', met: 3.5 },
  { name: 'Smith Machine Squat', category: 'Strength', met: 5.0 },
  { name: 'Hack Squat', category: 'Strength', met: 5.0 },
  { name: 'Sissy Squat', category: 'Strength', met: 4.0 },
  { name: 'Decline Bench Press', category: 'Strength', met: 5.0 },
  { name: 'Dumbbell Fly', category: 'Strength', met: 3.5 },
  { name: 'Incline Dumbbell Press', category: 'Strength', met: 4.5 },
  { name: 'Pec Deck', category: 'Strength', met: 3.5 },
  { name: 'Arnold Press', category: 'Strength', met: 4.0 },
  { name: 'Front Raise', category: 'Strength', met: 3.0 },
  { name: 'Rear Delt Fly', category: 'Strength', met: 3.0 },
  { name: 'Upright Row', category: 'Strength', met: 3.5 },
  { name: 'Barbell Curl', category: 'Strength', met: 3.5 },
  { name: 'Concentration Curl', category: 'Strength', met: 3.0 },
  { name: 'Cable Curl', category: 'Strength', met: 3.5 },
  { name: 'Reverse Curl', category: 'Strength', met: 3.0 },
  { name: 'Overhead Tricep Extension', category: 'Strength', met: 3.5 },
  { name: 'Diamond Push-up', category: 'Strength', met: 4.0 },
  { name: 'Assisted Pull-up', category: 'Strength', met: 3.5 },
  { name: 'Inverted Row', category: 'Strength', met: 3.5 },
  { name: 'Straight-arm Pulldown', category: 'Strength', met: 3.5 },
  { name: 'Renegade Row', category: 'Strength', met: 4.5 },
  { name: 'Farmer Carry', category: 'Strength', met: 5.0 },
  { name: 'Turkish Get-up', category: 'Strength', met: 5.0 },
  { name: 'Dumbbell Snatch', category: 'Strength', met: 7.0 },
  { name: 'Thruster', category: 'Strength', met: 7.0 },
  { name: 'Mountain Climber', category: 'Strength', met: 7.0 },
  { name: 'Bicycle Crunch', category: 'Strength', met: 3.0 },
  { name: 'Leg Raise', category: 'Strength', met: 3.0 },
  { name: 'Hanging Knee Raise', category: 'Strength', met: 3.5 },
  { name: 'Side Plank', category: 'Strength', met: 3.0 },
  { name: 'Bird Dog', category: 'Strength', met: 2.8 },
  { name: 'Pallof Press', category: 'Strength', met: 3.0 },
  { name: 'Barbell Box Squat', category: 'Strength', met: 5.0 },
  { name: 'Barbell Pin Squat', category: 'Strength', met: 4.5 },
  { name: 'Barbell Zercher Squat', category: 'Strength', met: 5.0 },
  { name: 'Barbell Overhead Squat', category: 'Strength', met: 5.5 },
  { name: 'Dumbbell Front Squat', category: 'Strength', met: 6.0 },
  { name: 'Dumbbell Split Squat', category: 'Strength', met: 4.5 },
  { name: 'Dumbbell Curtsy Lunge', category: 'Strength', met: 5.0 },
  { name: 'Dumbbell Lateral Lunge', category: 'Strength', met: 5.5 },
  { name: 'Dumbbell Step-up', category: 'Strength', met: 6.0 },
  { name: 'Dumbbell Reverse Step-up', category: 'Strength', met: 4.5 },
  { name: 'Dumbbell Sumo Squat', category: 'Strength', met: 5.0 },
  { name: 'Dumbbell Pulse Squat', category: 'Strength', met: 5.5 },
  { name: 'Kettlebell Goblet Squat', category: 'Strength', met: 6.0 },
  { name: 'Kettlebell Front Squat', category: 'Strength', met: 4.5 },
  { name: 'Kettlebell Lateral Lunge', category: 'Strength', met: 5.0 },
  { name: 'Kettlebell Reverse Lunge', category: 'Strength', met: 5.5 },
  { name: 'Kettlebell Step-up', category: 'Strength', met: 6.0 },
  { name: 'Landmine Squat', category: 'Strength', met: 4.5 },
  { name: 'Landmine Reverse Lunge', category: 'Strength', met: 5.0 },
  { name: 'Landmine Lateral Lunge', category: 'Strength', met: 5.5 },
  { name: 'Belt Squat', category: 'Strength', met: 6.0 },
  { name: 'Pendulum Squat', category: 'Strength', met: 4.5 },
  { name: 'Lever Squat', category: 'Strength', met: 5.0 },
  { name: 'Seated Leg Curl', category: 'Strength', met: 5.5 },
  { name: 'Lying Leg Curl', category: 'Strength', met: 6.0 },
  { name: 'Standing Leg Curl', category: 'Strength', met: 4.5 },
  { name: 'Nordic Hamstring Curl', category: 'Strength', met: 5.0 },
  { name: 'Glute Ham Raise', category: 'Strength', met: 4.0 },
  { name: 'Cable Pull-through', category: 'Strength', met: 3.5 },
  { name: 'Barbell Hip Thrust', category: 'Strength', met: 5.0 },
  { name: 'Single-leg Hip Thrust', category: 'Strength', met: 5.5 },
  { name: 'Banded Glute Bridge', category: 'Strength', met: 4.0 },
  { name: 'Single-leg Glute Bridge', category: 'Strength', met: 4.5 },
  { name: 'Reverse Hyperextension', category: 'Strength', met: 5.0 },
  { name: '45-degree Back Extension', category: 'Strength', met: 5.5 },
  { name: 'Donkey Calf Raise', category: 'Strength', met: 5.5 },
  { name: 'Seated Calf Raise', category: 'Strength', met: 6.0 },
  { name: 'Single-leg Calf Raise', category: 'Strength', met: 4.5 },
  { name: 'Tibialis Raise', category: 'Strength', met: 5.0 },
  { name: 'Dumbbell Bench Press', category: 'Strength', met: 4.5 },
  { name: 'Dumbbell Incline Bench Press', category: 'Strength', met: 5.0 },
  { name: 'Dumbbell Decline Bench Press', category: 'Strength', met: 5.5 },
  { name: 'Barbell Floor Press', category: 'Strength', met: 6.0 },
  { name: 'Dumbbell Floor Press', category: 'Strength', met: 3.5 },
  { name: 'Spoto Press', category: 'Strength', met: 6.0 },
  { name: 'Board Press', category: 'Strength', met: 3.5 },
  { name: 'Machine Chest Press', category: 'Strength', met: 4.0 },
  { name: 'Incline Machine Chest Press', category: 'Strength', met: 4.5 },
  { name: 'Decline Machine Chest Press', category: 'Strength', met: 5.0 },
  { name: 'Standing Cable Chest Press', category: 'Strength', met: 5.5 },
  { name: 'Low-to-high Cable Fly', category: 'Strength', met: 3.0 },
  { name: 'High-to-low Cable Fly', category: 'Strength', met: 3.5 },
  { name: 'Cable Crossover', category: 'Strength', met: 4.0 },
  { name: 'Dumbbell Pullover', category: 'Strength', met: 4.5 },
  { name: 'Machine Chest Fly', category: 'Strength', met: 2.8 },
  { name: 'Incline Push-up', category: 'Strength', met: 3.5 },
  { name: 'Decline Push-up', category: 'Strength', met: 4.0 },
  { name: 'Wide Push-up', category: 'Strength', met: 4.5 },
  { name: 'Archer Push-up', category: 'Strength', met: 5.0 },
  { name: 'Ring Push-up', category: 'Strength', met: 6.0 },
  { name: 'Ring Dip', category: 'Strength', met: 3.5 },
  { name: 'Barbell Pendlay Row', category: 'Strength', met: 4.0 },
  { name: 'Barbell Yates Row', category: 'Strength', met: 4.5 },
  { name: 'Barbell Seal Row', category: 'Strength', met: 5.0 },
  { name: 'Barbell Meadows Row', category: 'Strength', met: 5.5 },
  { name: 'Landmine T-bar Row', category: 'Strength', met: 3.5 },
  { name: 'Chest-supported T-bar Row', category: 'Strength', met: 4.0 },
  { name: 'Machine High Row', category: 'Strength', met: 4.5 },
  { name: 'Machine Low Row', category: 'Strength', met: 5.0 },
  { name: 'Chest-supported Dumbbell Row', category: 'Strength', met: 5.0 },
  { name: 'Incline Bench Dumbbell Row', category: 'Strength', met: 5.5 },
  { name: 'Dumbbell Pullover for Lats', category: 'Strength', met: 5.0 },
  { name: 'Straight-arm Cable Pulldown', category: 'Strength', met: 5.5 },
  { name: 'V-bar Pulldown', category: 'Strength', met: 3.5 },
  { name: 'Scapular Pull-up', category: 'Strength', met: 5.5 },
  { name: 'Band-assisted Chin-up', category: 'Strength', met: 3.5 },
  { name: 'Barbell Shrug', category: 'Strength', met: 3.0 },
  { name: 'Dumbbell Shrug', category: 'Strength', met: 3.5 },
  { name: 'Cable Shrug', category: 'Strength', met: 4.0 },
  { name: 'Barbell High Pull', category: 'Strength', met: 8.0 },
  { name: 'Dumbbell Shoulder Press', category: 'Strength', met: 4.5 },
  { name: 'Seated Dumbbell Shoulder Press', category: 'Strength', met: 5.0 },
  { name: 'Machine Shoulder Press', category: 'Strength', met: 5.5 },
  { name: 'Half-kneeling Landmine Press', category: 'Strength', met: 3.5 },
  { name: 'Push Press', category: 'Strength', met: 7.0 },
  { name: 'Z Press', category: 'Strength', met: 4.0 },
  { name: 'Barbell Front Raise', category: 'Strength', met: 2.8 },
  { name: 'Cable Lateral Raise', category: 'Strength', met: 3.0 },
  { name: 'Machine Lateral Raise', category: 'Strength', met: 4.0 },
  { name: 'Dumbbell Y Raise', category: 'Strength', met: 2.8 },
  { name: 'Cable Rear Delt Fly', category: 'Strength', met: 3.0 },
  { name: 'Reverse Pec Deck', category: 'Strength', met: 3.5 },
  { name: 'Band Pull-apart', category: 'Strength', met: 4.0 },
  { name: 'Dumbbell External Rotation', category: 'Strength', met: 2.8 },
  { name: 'Cable External Rotation', category: 'Strength', met: 3.0 },
  { name: 'Barbell Spider Curl', category: 'Strength', met: 3.5 },
  { name: 'Incline Dumbbell Curl', category: 'Strength', met: 4.0 },
  { name: 'Bayesian Cable Curl', category: 'Strength', met: 2.8 },
  { name: 'Cable Rope Hammer Curl', category: 'Strength', met: 3.0 },
  { name: 'Dumbbell Zottman Curl', category: 'Strength', met: 3.5 },
  { name: 'Dumbbell Waiter Curl', category: 'Strength', met: 4.0 },
  { name: 'Barbell Reverse Curl', category: 'Strength', met: 2.8 },
  { name: 'Wrist Curl', category: 'Strength', met: 3.0 },
  { name: 'Reverse Wrist Curl', category: 'Strength', met: 3.5 },
  { name: 'Wrist Roller', category: 'Strength', met: 4.0 },
  { name: 'Cable Tricep Kickback', category: 'Strength', met: 2.8 },
  { name: 'Dumbbell Tricep Kickback', category: 'Strength', met: 3.0 },
  { name: 'Cable Overhead Tricep Extension', category: 'Strength', met: 3.5 },
  { name: 'Dumbbell Overhead Tricep Extension', category: 'Strength', met: 4.0 },
  { name: 'EZ-bar Skull Crusher', category: 'Strength', met: 3.0 },
  { name: 'Incline Skull Crusher', category: 'Strength', met: 3.5 },
  { name: 'Bench Dip', category: 'Strength', met: 5.0 },
  { name: 'Cable Wrist Extension', category: 'Strength', met: 2.8 },
  { name: 'Barbell Wrist Curl', category: 'Strength', met: 3.0 },
  { name: 'Hollow-body Hold', category: 'Strength', met: 3.5 },
  { name: 'Hollow-body Rock', category: 'Strength', met: 4.0 },
  { name: 'Ab Wheel Rollout', category: 'Strength', met: 4.5 },
  { name: 'Kneeling Ab Wheel Rollout', category: 'Strength', met: 2.8 },
  { name: 'Cable Crunch', category: 'Strength', met: 3.0 },
  { name: 'Decline Sit-up', category: 'Strength', met: 3.5 },
  { name: 'V-up', category: 'Strength', met: 4.5 },
  { name: 'Reverse Crunch', category: 'Strength', met: 2.8 },
  { name: 'Hanging Leg Raise', category: 'Strength', met: 3.0 },
  { name: 'Captain Chair Knee Raise', category: 'Strength', met: 3.5 },
  { name: 'Cable Wood Chop', category: 'Strength', met: 4.0 },
  { name: 'Landmine Rotation', category: 'Strength', met: 4.5 },
  { name: 'Plank Shoulder Tap', category: 'Strength', met: 3.5 },
  { name: 'Plank Reach', category: 'Strength', met: 4.0 },
  { name: 'Copenhagen Plank', category: 'Strength', met: 4.5 },
  { name: 'Suitcase Carry', category: 'Strength', met: 5.5 },
  { name: 'Overhead Carry', category: 'Strength', met: 6.0 },
  { name: 'Waiter Carry', category: 'Strength', met: 5.0 },
  { name: 'Rack Carry', category: 'Strength', met: 5.5 },
  { name: 'Barbell Chest Press', category: 'Strength', met: 5.0 },
  { name: 'Incline Barbell Chest Press', category: 'Strength', met: 5.0 },
  { name: 'Decline Barbell Chest Press', category: 'Strength', met: 5.0 },
  { name: 'Dumbbell Chest Press', category: 'Strength', met: 4.5 },
  { name: 'Incline Dumbbell Chest Press', category: 'Strength', met: 4.5 },
  { name: 'Decline Dumbbell Chest Press', category: 'Strength', met: 4.5 },
  { name: 'Incline Chest Press', category: 'Strength', met: 5.0 },
  { name: 'Decline Chest Press', category: 'Strength', met: 5.0 },
  { name: 'Smith Machine Chest Press', category: 'Strength', met: 4.5 },
  { name: 'Incline Smith Machine Chest Press', category: 'Strength', met: 4.5 },
  { name: 'Decline Smith Machine Chest Press', category: 'Strength', met: 4.5 },
  { name: 'Cable Chest Press', category: 'Strength', met: 4.0 },
  { name: 'Incline Cable Chest Press', category: 'Strength', met: 4.0 },
  { name: 'Decline Cable Chest Press', category: 'Strength', met: 4.0 },
  { name: 'Dumbbell Chest Fly', category: 'Strength', met: 3.5 },
  { name: 'Incline Dumbbell Chest Fly', category: 'Strength', met: 3.5 },
  { name: 'Decline Dumbbell Chest Fly', category: 'Strength', met: 3.5 },
  { name: 'Incline Cable Chest Fly', category: 'Strength', met: 3.5 },
  { name: 'Decline Cable Chest Fly', category: 'Strength', met: 3.5 },
  { name: 'Chest Dip', category: 'Strength', met: 4.0 },
  { name: 'Pec Deck Fly', category: 'Strength', met: 3.5 },
  { name: 'Dumbbell Squeeze Press', category: 'Strength', met: 4.5 },
  { name: 'Guillotine Press', category: 'Strength', met: 5.0 },
  { name: 'Floor Chest Press', category: 'Strength', met: 4.5 },
  { name: 'Leverage Chest Press', category: 'Strength', met: 4.5 },
  { name: 'Plate-Loaded Chest Press', category: 'Strength', met: 4.5 },
  { name: 'Standing Cable Fly', category: 'Strength', met: 3.5 },
  { name: 'Kneeling Cable Fly', category: 'Strength', met: 3.5 },
  { name: 'Resistance Band Chest Press', category: 'Strength', met: 3.5 },
  { name: 'Resistance Band Chest Fly', category: 'Strength', met: 3.5 },
  { name: 'Ring Chest Fly', category: 'Strength', met: 4.0 },
  { name: 'Suspension Trainer Chest Press', category: 'Strength', met: 4.0 },
  { name: 'Svend Press', category: 'Strength', met: 3.5 },
  { name: 'Hex Press', category: 'Strength', met: 4.0 },
  { name: 'Landmine Chest Press', category: 'Strength', met: 4.5 },
  { name: 'Push-up Plus', category: 'Strength', met: 3.8 },
  { name: 'Decline Dumbbell Fly', category: 'Strength', met: 3.5 },
  { name: 'Machine Incline Fly', category: 'Strength', met: 3.5 },
  { name: 'Machine Decline Fly', category: 'Strength', met: 3.5 },
  { name: 'Ring Chest Press', category: 'Strength', met: 4.0 },
  { name: 'Standing Cable Crossover', category: 'Strength', met: 4.0 },
  { name: 'Barbell Dead Row', category: 'Strength', met: 4.5 },
  { name: 'Dumbbell Pullover Row', category: 'Strength', met: 4.0 },
  { name: 'Machine Chest-Supported Row', category: 'Strength', met: 4.0 },
  { name: 'Machine Row', category: 'Strength', met: 4.0 },
  { name: 'Iso-Lateral Row', category: 'Strength', met: 4.5 },
  { name: 'Lever Row', category: 'Strength', met: 4.0 },
  { name: 'T-Bar Row', category: 'Strength', met: 4.5 },
  { name: 'Assisted Chin-up', category: 'Strength', met: 3.5 },
  { name: 'Rack Pull', category: 'Strength', met: 5.0 },
  { name: 'Inverted Pull-up', category: 'Strength', met: 3.5 },
  { name: 'Bodyweight Row', category: 'Strength', met: 3.5 },
  { name: 'Seal Row', category: 'Strength', met: 4.0 },
  { name: 'Meadows Row', category: 'Strength', met: 4.5 },
  { name: 'Landmine Row', category: 'Strength', met: 4.5 },
  { name: 'Cable Pullover', category: 'Strength', met: 3.5 },
  { name: 'Barbell Pullover', category: 'Strength', met: 4.0 },
  { name: 'Seated Dumbbell Press', category: 'Strength', met: 4.0 },
  { name: 'Standing Dumbbell Press', category: 'Strength', met: 4.5 },
  { name: 'Seated Barbell Press', category: 'Strength', met: 4.5 },
  { name: 'Machine Arnold Press', category: 'Strength', met: 4.0 },
  { name: 'Cable Shoulder Press', category: 'Strength', met: 4.0 },
  { name: 'Landmine Shoulder Press', category: 'Strength', met: 4.5 },
  { name: 'Dumbbell Front Raise', category: 'Strength', met: 3.0 },
  { name: 'Cable Front Raise', category: 'Strength', met: 3.0 },
  { name: 'Plate Front Raise', category: 'Strength', met: 3.0 },
  { name: 'Dumbbell Rear Delt Raise', category: 'Strength', met: 3.0 },
  { name: 'Cable Rear Delt Raise', category: 'Strength', met: 3.0 },
  { name: 'Reverse Fly Machine', category: 'Strength', met: 3.0 },
  { name: 'Machine Front Raise', category: 'Strength', met: 3.0 },
  { name: 'Kettlebell High Pull', category: 'Strength', met: 5.0 },
  { name: 'Kettlebell Shrug', category: 'Strength', met: 3.5 },
  { name: 'Machine Shrug', category: 'Strength', met: 3.5 },
  { name: 'Cable Upright Row', category: 'Strength', met: 3.5 },
  { name: 'Dumbbell Upright Row', category: 'Strength', met: 3.5 },
  { name: 'Shoulder Press Machine', category: 'Strength', met: 4.0 },
  { name: 'Shoulder Y Raise', category: 'Strength', met: 3.0 },
  { name: 'Machine Shoulder Raise', category: 'Strength', met: 3.0 },
  { name: 'EZ-bar Curl', category: 'Strength', met: 3.5 },
  { name: 'Cable Preacher Curl', category: 'Strength', met: 3.5 },
  { name: 'Machine Preacher Curl', category: 'Strength', met: 3.5 },
  { name: 'Spider Curl', category: 'Strength', met: 3.5 },
  { name: 'Machine Hammer Curl', category: 'Strength', met: 3.5 },
  { name: 'Bayesian Curl', category: 'Strength', met: 3.5 },
  { name: 'Zottman Curl', category: 'Strength', met: 3.5 },
  { name: 'Waiter Curl', category: 'Strength', met: 3.0 },
  { name: 'Dumbbell Reverse Curl', category: 'Strength', met: 3.0 },
  { name: 'EZ-bar Reverse Curl', category: 'Strength', met: 3.0 },
  { name: 'Cable Hammer Curl', category: 'Strength', met: 3.5 },
  { name: 'Rope Hammer Curl', category: 'Strength', met: 3.5 },
  { name: 'Machine Bicep Curl', category: 'Strength', met: 3.5 },
  { name: 'Incline Cable Curl', category: 'Strength', met: 3.5 },
  { name: 'High Cable Curl', category: 'Strength', met: 3.5 },
  { name: 'Low Cable Curl', category: 'Strength', met: 3.5 },
  { name: 'Finger Curl', category: 'Strength', met: 3.0 },
  { name: 'Cable Bicep Curl', category: 'Strength', met: 3.5 },
  { name: 'Cable Wrist Curl', category: 'Strength', met: 3.0 },
  { name: 'Plate Pinch', category: 'Strength', met: 3.0 },
  { name: 'Rope Pushdown', category: 'Strength', met: 3.5 },
  { name: 'V-bar Pushdown', category: 'Strength', met: 3.5 },
  { name: 'Straight-bar Pushdown', category: 'Strength', met: 3.5 },
  { name: 'Cable Overhead Extension', category: 'Strength', met: 3.5 },
  { name: 'Dumbbell Overhead Extension', category: 'Strength', met: 3.5 },
  { name: 'Barbell French Press', category: 'Strength', met: 3.5 },
  { name: 'Dumbbell Skull Crusher', category: 'Strength', met: 3.5 },
  { name: 'JM Press', category: 'Strength', met: 4.0 },
  { name: 'Bodyweight Triceps Dip', category: 'Strength', met: 4.0 },
  { name: 'Assisted Dip', category: 'Strength', met: 3.5 },
  { name: 'Machine Dip', category: 'Strength', met: 4.0 },
  { name: 'Cable Kickback', category: 'Strength', met: 3.0 },
  { name: 'Dumbbell Tate Press', category: 'Strength', met: 3.5 },
  { name: 'Barbell Tate Press', category: 'Strength', met: 3.5 },
  { name: 'Tricep Extension Machine', category: 'Strength', met: 3.5 },
  { name: 'Lying Tricep Extension', category: 'Strength', met: 3.5 },
  { name: 'Seated Tricep Extension', category: 'Strength', met: 3.5 },
  { name: 'Tricep Bench Press', category: 'Strength', met: 4.0 },
  { name: 'Dumbbell Triceps Extension', category: 'Strength', met: 3.5 },
  { name: 'Barbell Hack Squat', category: 'Strength', met: 5.0 },
  { name: 'Dumbbell Hack Squat', category: 'Strength', met: 5.0 },
  { name: 'Leg Press Squat', category: 'Strength', met: 5.0 },
  { name: 'Single-leg Leg Press', category: 'Strength', met: 4.5 },
  { name: 'Leg Extension Machine', category: 'Strength', met: 3.5 },
  { name: 'Seated Hamstring Curl', category: 'Strength', met: 3.5 },
  { name: 'Lying Hamstring Curl', category: 'Strength', met: 3.5 },
  { name: 'Standing Hamstring Curl', category: 'Strength', met: 3.5 },
  { name: 'Cable Hamstring Curl', category: 'Strength', met: 3.5 },
  { name: 'Dumbbell Romanian Deadlift', category: 'Strength', met: 5.0 },
  { name: 'Barbell Stiff-leg Deadlift', category: 'Strength', met: 5.0 },
  { name: 'Nordic Curl', category: 'Strength', met: 5.0 },
  { name: 'Reverse Nordic Curl', category: 'Strength', met: 4.0 },
  { name: 'Sissy Squat Machine', category: 'Strength', met: 4.0 },
  { name: 'Wall Sit', category: 'Strength', met: 3.5 },
  { name: 'Jefferson Squat', category: 'Strength', met: 5.0 },
  { name: 'Cyclist Squat', category: 'Strength', met: 5.0 },
  { name: 'Single-leg Hack Squat', category: 'Strength', met: 4.5 },
  { name: 'Box Step-up', category: 'Strength', met: 4.5 },
  { name: 'Kettlebell Split Squat', category: 'Strength', met: 5.0 },
  { name: 'Barbell Glute Bridge', category: 'Strength', met: 4.5 },
  { name: 'Dumbbell Glute Bridge', category: 'Strength', met: 4.0 },
  { name: 'Cable Glute Kickback', category: 'Strength', met: 3.5 },
  { name: 'Machine Glute Kickback', category: 'Strength', met: 3.5 },
  { name: 'Hip Abduction Machine', category: 'Strength', met: 3.0 },
  { name: 'Cable Hip Abduction', category: 'Strength', met: 3.0 },
  { name: 'Banded Hip Abduction', category: 'Strength', met: 3.0 },
  { name: 'Hip Adduction Machine', category: 'Strength', met: 3.0 },
  { name: 'Cable Hip Adduction', category: 'Strength', met: 3.0 },
  { name: 'Frog Pump', category: 'Strength', met: 3.5 },
  { name: 'Glute Drive Machine', category: 'Strength', met: 4.5 },
  { name: 'Quadruped Hip Extension', category: 'Strength', met: 3.0 },
  { name: 'Donkey Kick', category: 'Strength', met: 3.0 },
  { name: 'Fire Hydrant', category: 'Strength', met: 3.0 },
  { name: 'Barbell Good Morning', category: 'Strength', met: 4.5 },
  { name: 'Cable Hip Extension', category: 'Strength', met: 3.5 },
  { name: 'Hip Extension', category: 'Strength', met: 3.5 },
  { name: 'Cable Glute Extension', category: 'Strength', met: 3.5 },
  { name: 'Glute Bridge Machine', category: 'Strength', met: 4.0 },
  { name: 'Hip Thrust Machine', category: 'Strength', met: 4.5 },
  { name: 'Jackknife Sit-up', category: 'Strength', met: 3.5 },
  { name: 'Weighted Crunch', category: 'Strength', met: 3.0 },
  { name: 'Cable Side Bend', category: 'Strength', met: 3.0 },
  { name: 'Dumbbell Side Bend', category: 'Strength', met: 3.0 },
  { name: 'Barbell Side Bend', category: 'Strength', met: 3.0 },
  { name: 'L-sit', category: 'Strength', met: 3.5 },
  { name: 'Captain Chair Leg Raise', category: 'Strength', met: 3.5 },
  { name: 'Flutter Kicks', category: 'Strength', met: 3.0 },
  { name: 'Hollow Body Hold', category: 'Strength', met: 3.0 },
  { name: 'Superman Hold', category: 'Strength', met: 2.8 },
  { name: 'Abdominal Crunch Machine', category: 'Strength', met: 3.0 },
  { name: 'Ab Coaster', category: 'Strength', met: 3.0 },
  { name: 'Medicine Ball Twist', category: 'Strength', met: 3.5 },
  { name: 'Medicine Ball Sit-up', category: 'Strength', met: 3.5 },
  { name: 'Cable Reverse Crunch', category: 'Strength', met: 3.5 },
  { name: 'Lying Leg Raise', category: 'Strength', met: 3.0 },
  { name: 'Heel Tap', category: 'Strength', met: 3.0 },
  { name: 'Toe Touch Crunch', category: 'Strength', met: 3.0 },
  { name: 'Back Extension Hold', category: 'Strength', met: 3.0 },
  { name: 'Stability Ball Crunch', category: 'Strength', met: 3.0 },
  { name: 'Barbell Clean', category: 'Strength', met: 7.0 },
  { name: 'Power Clean', category: 'Strength', met: 7.0 },
  { name: 'Hang Clean', category: 'Strength', met: 7.0 },
  { name: 'Barbell Snatch', category: 'Strength', met: 7.0 },
  { name: 'Power Snatch', category: 'Strength', met: 7.0 },
  { name: 'Clean and Jerk', category: 'Strength', met: 7.5 },
  { name: 'Barbell Thruster', category: 'Strength', met: 7.0 },
  { name: 'Dumbbell Thruster', category: 'Strength', met: 7.0 },
  { name: 'Kettlebell Clean', category: 'Strength', met: 6.0 },
  { name: 'Kettlebell Snatch', category: 'Strength', met: 7.0 },
  { name: 'Kettlebell Turkish Get-up', category: 'Strength', met: 5.0 },
  { name: 'Dumbbell Turkish Get-up', category: 'Strength', met: 5.0 },
  { name: 'Sandbag Carry', category: 'Strength', met: 5.5 },
  { name: 'Sled Drag', category: 'Strength', met: 6.0 },
  { name: 'Sled March', category: 'Strength', met: 6.0 },
  { name: 'Bear Crawl', category: 'Strength', met: 5.0 },
  { name: 'Crab Walk', category: 'Strength', met: 4.0 },
  { name: 'Wall Ball', category: 'Strength', met: 6.0 },
  { name: 'Dumbbell Man Maker', category: 'Strength', met: 7.0 },
  { name: 'Barbell Complex', category: 'Strength', met: 7.0 },

  // Cardio exercises
  { name: 'Running', category: 'Cardio', met: 9.8 },
  { name: 'Jogging', category: 'Cardio', met: 7.0 },
  { name: 'Cycling', category: 'Cardio', met: 7.5 },
  { name: 'Jump Rope', category: 'Cardio', met: 10.0 },
  { name: 'Rowing Machine', category: 'Cardio', met: 7.0 },
  { name: 'Elliptical', category: 'Cardio', met: 5.0 },
  { name: 'Stair Climber', category: 'Cardio', met: 8.0 },
  { name: 'Swimming', category: 'Cardio', met: 8.0 },
  { name: 'Walking', category: 'Cardio', met: 3.5 },
  { name: 'Brisk Walking', category: 'Cardio', met: 4.5 },
  { name: 'Hiking', category: 'Cardio', met: 6.0 },
  { name: 'Treadmill Walking', category: 'Cardio', met: 4.0 },
  { name: 'Treadmill Running', category: 'Cardio', met: 9.8 },
  { name: 'Indoor Cycling', category: 'Cardio', met: 7.5 },
  { name: 'Mountain Biking', category: 'Cardio', met: 8.5 },
  { name: 'Spin Class', category: 'Cardio', met: 8.5 },
  { name: 'Water Aerobics', category: 'Cardio', met: 5.5 },
  { name: 'Dancing', category: 'Cardio', met: 5.5 },
  { name: 'Zumba', category: 'Cardio', met: 6.5 },
  { name: 'Tennis', category: 'Cardio', met: 7.3 },
  { name: 'Basketball', category: 'Cardio', met: 6.5 },
  { name: 'Soccer', category: 'Cardio', met: 7.0 },
  { name: 'Badminton', category: 'Cardio', met: 5.5 },
  { name: 'Boxing', category: 'Cardio', met: 7.8 },
  { name: 'Kickboxing', category: 'Cardio', met: 7.5 },
  { name: 'Hula Hooping', category: 'Cardio', met: 5.5 },
  { name: 'Jumping Jacks', category: 'Cardio', met: 7.0 },
  { name: 'Hiking Uphill', category: 'Cardio', met: 7.0 },
  { name: 'Cross-country Skiing', category: 'Cardio', met: 8.0 },
  { name: 'Water Polo', category: 'Cardio', met: 10.0 },
  { name: 'Battle Ropes', category: 'Cardio', met: 9.0 },
  { name: 'Sled Push', category: 'Cardio', met: 8.0 },
  { name: 'Sled Pull', category: 'Cardio', met: 7.5 },
  { name: 'Boxing, punching bag', category: 'Cardio', met: 7.8 },
  { name: 'Martial Arts', category: 'Cardio', met: 10.0 },
  { name: 'Wrestling', category: 'Cardio', met: 6.0 },
  { name: 'Racquetball', category: 'Cardio', met: 7.0 },
  { name: 'Squash', category: 'Cardio', met: 7.3 },
  { name: 'Volleyball', category: 'Cardio', met: 4.0 },
  { name: 'Beach Volleyball', category: 'Cardio', met: 8.0 },
  { name: 'Softball', category: 'Cardio', met: 5.0 },
  { name: 'Flag Football', category: 'Cardio', met: 7.0 },
  { name: 'Skating', category: 'Cardio', met: 7.0 },
  { name: 'Rollerblading', category: 'Cardio', met: 7.5 },
  { name: 'Snowboarding', category: 'Cardio', met: 5.3 },
  { name: 'Downhill Skiing', category: 'Cardio', met: 5.3 },
  { name: 'Cross-country Ski Machine', category: 'Cardio', met: 6.8 },
  { name: 'Kayaking', category: 'Cardio', met: 5.0 },
  { name: 'Canoeing', category: 'Cardio', met: 3.5 },
  { name: 'Paddleboarding', category: 'Cardio', met: 6.0 },
  { name: 'Surfing', category: 'Cardio', met: 3.0 },
  { name: 'Water jogging', category: 'Cardio', met: 6.0 },
  { name: 'Freestyle swimming', category: 'Cardio', met: 8.0 },
  { name: 'Breaststroke swimming', category: 'Cardio', met: 10.0 },
  { name: 'Lap swimming, leisurely', category: 'Cardio', met: 6.0 },
  { name: 'Jump rope, moderate', category: 'Cardio', met: 11.8 },
  { name: 'Jump rope, fast', category: 'Cardio', met: 12.3 },
  { name: 'Stair climbing', category: 'Cardio', met: 8.8 },
  { name: 'Step aerobics', category: 'Cardio', met: 6.5 },
  { name: 'Aerobics, low impact', category: 'Cardio', met: 5.0 },
  { name: 'Aerobics, high impact', category: 'Cardio', met: 7.3 },
  { name: 'HIIT', category: 'Cardio', met: 8.0 },
  { name: 'Circuit training', category: 'Cardio', met: 6.0 },
  { name: 'Boot camp workout', category: 'Cardio', met: 7.0 },
  { name: 'Pilates', category: 'Cardio', met: 3.0 },
  { name: 'Yoga, Hatha', category: 'Cardio', met: 2.5 },
  { name: 'Yoga, power', category: 'Cardio', met: 4.0 },
  { name: 'Tai chi', category: 'Cardio', met: 3.0 },
  { name: 'Marching in place', category: 'Cardio', met: 3.5 },
  { name: 'Running, intervals', category: 'Cardio', met: 11.0 },
  { name: 'Running, uphill', category: 'Cardio', met: 11.0 },
  { name: 'Trail running', category: 'Cardio', met: 9.0 },
  { name: 'Track running', category: 'Cardio', met: 9.8 },
  { name: 'Stroller walking', category: 'Cardio', met: 3.5 },
  { name: 'Dog walking', category: 'Cardio', met: 3.0 },
  { name: 'Recumbent cycling', category: 'Cardio', met: 5.0 },
  { name: 'Stationary bike, vigorous', category: 'Cardio', met: 8.8 },
  { name: 'Rowing, vigorous', category: 'Cardio', met: 8.5 },
  { name: 'Dance cardio', category: 'Cardio', met: 7.0 },
  { name: 'Line dancing', category: 'Cardio', met: 4.5 },
  { name: 'Ballet', category: 'Cardio', met: 5.0 },
  { name: 'Cheerleading', category: 'Cardio', met: 6.0 },
  { name: 'Gardening', category: 'Cardio', met: 3.5 },
  { name: 'Raking leaves', category: 'Cardio', met: 4.0 },
  { name: 'Mowing lawn', category: 'Cardio', met: 5.5 },
  { name: 'Easy outdoor run', category: 'Cardio', met: 7.0 },
  { name: 'Moderate outdoor run', category: 'Cardio', met: 9.0 },
  { name: 'Fast outdoor run', category: 'Cardio', met: 11.5 },
  { name: 'Easy treadmill jog', category: 'Cardio', met: 7.0 },
  { name: 'Treadmill run, moderate', category: 'Cardio', met: 9.0 },
  { name: 'Treadmill run, fast', category: 'Cardio', met: 11.5 },
  { name: 'Incline treadmill walk', category: 'Cardio', met: 5.0 },
  { name: 'Incline treadmill run', category: 'Cardio', met: 10.0 },
  { name: 'Outdoor power walking', category: 'Cardio', met: 5.0 },
  { name: 'Walking, brisk uphill', category: 'Cardio', met: 6.0 },
  { name: 'Walking, leisurely', category: 'Cardio', met: 2.8 },
  { name: 'Walking, moderate pace', category: 'Cardio', met: 3.5 },
  { name: 'Walking, fast pace', category: 'Cardio', met: 4.8 },
  { name: 'Stationary cycling, light', category: 'Cardio', met: 4.0 },
  { name: 'Stationary cycling, moderate', category: 'Cardio', met: 6.8 },
  { name: 'Stationary cycling, vigorous', category: 'Cardio', met: 10.0 },
  { name: 'Outdoor cycling, easy', category: 'Cardio', met: 4.0 },
  { name: 'Outdoor cycling, moderate', category: 'Cardio', met: 7.5 },
  { name: 'Outdoor cycling, vigorous', category: 'Cardio', met: 10.0 },
  { name: 'Upright bike intervals', category: 'Cardio', met: 8.0 },
  { name: 'Recumbent bike, moderate', category: 'Cardio', met: 5.5 },
  { name: 'Rowing machine, light', category: 'Cardio', met: 4.8 },
  { name: 'Rowing machine, moderate', category: 'Cardio', met: 7.0 },
  { name: 'Rowing machine, intervals', category: 'Cardio', met: 10.0 },
  { name: 'Elliptical, light', category: 'Cardio', met: 4.5 },
  { name: 'Elliptical, moderate', category: 'Cardio', met: 5.5 },
  { name: 'Elliptical, vigorous', category: 'Cardio', met: 9.0 },
  { name: 'Stair climber, moderate', category: 'Cardio', met: 6.5 },
  { name: 'Stair climber, vigorous', category: 'Cardio', met: 9.0 },
  { name: 'Swimming, backstroke', category: 'Cardio', met: 7.0 },
  { name: 'Swimming, sidestroke', category: 'Cardio', met: 7.0 },
  { name: 'Swimming, butterfly', category: 'Cardio', met: 13.8 },
  { name: 'Water jogging, moderate', category: 'Cardio', met: 6.0 },
  { name: 'Jump rope, easy pace', category: 'Cardio', met: 8.8 },
  { name: 'Jump rope, alternating feet', category: 'Cardio', met: 11.0 },
  { name: 'Dance, social', category: 'Cardio', met: 4.5 },
  { name: 'Dancing, vigorous', category: 'Cardio', met: 7.0 },
  { name: 'Boxing, sparring', category: 'Cardio', met: 9.0 },
  { name: 'Basketball, shooting drills', category: 'Cardio', met: 4.5 },
  { name: 'Soccer, practice drills', category: 'Cardio', met: 7.0 },
]

export const CATEGORIES = ['Strength', 'Cardio']

export function listCustomExercises() {
  const stored = localStorage.getItem(CUSTOM_EXERCISES_KEY)
  if (!stored) return []

  try {
    const exercises = JSON.parse(stored)
    if (Array.isArray(exercises)) return exercises
  } catch {
    localStorage.removeItem(CUSTOM_EXERCISES_KEY)
  }
  return []
}

export function addCustomExercise(input) {
  const name = input.name.trim()
  const met = Number(input.met)
  const category = input.category

  if (!name || name.length > 100) {
    throw new Error('Exercise name must be between 1 and 100 characters.')
  }
  if (!Number.isFinite(met) || met < 0.1 || met > 20) {
    throw new Error('MET must be between 0.1 and 20.')
  }
  if (!CATEGORIES.includes(category)) {
    throw new Error('Choose Strength or Cardio as the exercise category.')
  }

  const exercises = listCustomExercises()
  const exists = [...EXERCISE_CATALOG, ...exercises].some(
    (exercise) => exercise.name.toLowerCase() === name.toLowerCase()
  )
  if (exists) throw new Error('An exercise with that name already exists.')

  const exercise = { name, category, met }
  localStorage.setItem(CUSTOM_EXERCISES_KEY, JSON.stringify([...exercises, exercise]))
  return exercise
}

export function deleteCustomExercise(name) {
  const exercises = listCustomExercises()
  const remaining = exercises.filter((exercise) => exercise.name !== name)
  if (remaining.length === exercises.length) {
    throw new Error('Custom exercise was not found.')
  }
  localStorage.setItem(CUSTOM_EXERCISES_KEY, JSON.stringify(remaining))
  return remaining
}

export const MET_TABLE = Object.fromEntries(
  EXERCISE_CATALOG.map((exercise) => [exercise.name, exercise.met])
)
MET_TABLE.Default = 5.0

export function getMET(exercise) {
  if (Object.hasOwn(MET_TABLE, exercise)) return MET_TABLE[exercise]
  return listCustomExercises().find((item) => item.name === exercise)?.met ?? MET_TABLE.Default
}

export function getExerciseCategory(name) {
  return (
    EXERCISE_CATALOG.find((exercise) => exercise.name === name)?.category ??
    listCustomExercises().find((exercise) => exercise.name === name)?.category ??
    'Strength'
  )
}

export function calculateCalories(sets, bodyWeightKg, durationMinutes) {
  if (!sets || sets.length === 0) return 0
  const avgMet = sets.reduce((sum, s) => sum + getMET(s.exercise), 0) / sets.length
  const durationHours = durationMinutes / 60
  return Math.round(avgMet * bodyWeightKg * durationHours)
}